import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
import { config } from "../config.js";
import * as schema from "./schema.js";

/** Single shared postgres connection pool + Drizzle instance. */
const queryClient = postgres(config.databaseUrl, { max: 10 });

export const db = drizzle(queryClient, { schema });
export { schema };

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Apply pending Drizzle migrations. Migrations (generated by `drizzle-kit
 * generate` into ./drizzle) are the single source of truth for the schema.
 */
export async function runMigrations(): Promise<void> {
  const migrationsFolder = resolve(__dirname, "..", "..", "drizzle");
  await migrate(db, { migrationsFolder });
}

export async function closeDb(): Promise<void> {
  await queryClient.end({ timeout: 5 });
}
